###
GET http://localhost:8001/api/v1/hotels
Content-Type: application/json

###
POST http://localhost:8001/api/v1/hotels/
Content-Type: application/json


###
PUT http://localhost:8001/api/v1/hotels/12323
Content-Type: application/json

{
    "name":"Kevin"
}

###
DELETE http://localhost:8001/api/v1/hotels/12323
Content-Type: application/json

